---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'El software de clasificación de datos debe ejecutarse en un host que cumpla con los requisitos específicos del sistema operativo, requisitos de RAM, requisitos de software, etc.  Al implementar la clasificación de datos en la nube, se recomienda utilizar un sistema con características "grandes" para obtener una funcionalidad completa.' 
---
= Tipos de instancias de NetApp Data Classification compatibles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software NetApp Data Classification debe ejecutarse en un host que cumpla los requisitos específicos del sistema operativo, de RAM y de software. Cuando implementes Data Classification en la nube, te recomendamos que uses un sistema con las características "large" para obtener toda la funcionalidad.

En las tablas siguientes, si el sistema marcado como "predeterminado" no está disponible en la región en la que estás instalando Data Classification, se desplegará el siguiente tipo de instancia enumerado en la tabla.



== Tipos de instancias de AWS

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Extra grande | 32 CPU, 128 GB de RAM, 1 TiB gp3 SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.8xlarge"^](por defecto) 


| Grande | 16 CPU, 64 GB de RAM, SSD de 500 GiB | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xlarge"^](predeterminado) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 
|===


== Tipos de instancias de Azure

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Extra grande | 32 CPU, 128 GB de RAM, disco de SO (2048 GiB, rendimiento mínimo de 250 MB/s) y disco de datos (SSD de 1 TiB, rendimiento mínimo de 750 MB/s) | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dv3-series["Standard_D32_v3"^](por defecto) 


| Grande | 16 CPU, 64 GB de RAM, SSD de 500 GiB | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dsv3-series["Standard_D16s_v3"^](por defecto) 
|===


== Tipos de instancias de GCP

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, SSD de 500 GiB | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-estándar-16"^](predeterminado) n2d-standard-16 n1-standard-16 
|===