---
sidebar: sidebar 
permalink: task-scanning-overview.html 
keywords: cloud compliance, get started, enable cloud compliance, cifs credentials, smb credentials, cloud compliance access, privacy, compliance, dp volumes, data protection volumes, CVO, Cloud Volumes ONTAP, data sense, cloud data sense, mapping-only scans, map and classify, map & classify 
summary: Escanee sus fuentes de datos con NetApp Data Classification. 
---
= Escanee fuentes de datos con NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification escanea los datos en los repositorios (los volúmenes, esquemas de bases de datos u otros datos de usuario) que seleccione para identificar datos personales y confidenciales.  Luego, la clasificación de datos mapea los datos de su organización, categoriza cada archivo e identifica patrones predefinidos en los datos.  El resultado del escaneo es un índice de información personal, información personal confidencial, categorías de datos y tipos de archivos.

Después del escaneo inicial, la clasificación de datos escanea continuamente sus datos de manera rotatoria para detectar cambios incrementales.  Por eso es importante mantener la instancia en ejecución.

Puede habilitar y deshabilitar escaneos a nivel de volumen o a nivel de esquema de base de datos.



== ¿Cuál es la diferencia entre los escaneos de mapeo y clasificación?

Puede realizar dos tipos de escaneos en Clasificación de datos:

* Los escaneos de solo mapeo brindan únicamente una descripción general de alto nivel de sus datos y se realizan en fuentes de datos seleccionadas.  Los escaneos de solo mapeo toman menos tiempo que los escaneos de mapas y clasificación porque no acceden a los archivos para ver los datos dentro.  Es posible que desees hacer esto inicialmente para identificar áreas de investigación y luego realizar un escaneo de Mapa y Clasificación en esas áreas.
* **Los escaneos de mapas y clasificación** proporcionan un escaneo de nivel profundo de sus datos.


La siguiente tabla muestra algunas de las diferencias:

[cols="47,18,18"]
|===
| Característica | Mapear y clasificar escaneos | Escaneos de solo mapeo 


| Velocidad de escaneo | Lento | Rápido 


| Precios | Gratis | Gratis 


| Capacidad | Limitado a 500 TiB* | Limitado a 500 TiB* 


| Lista de tipos de archivos y capacidad utilizada | Sí | Sí 


| Número de archivos y capacidad utilizada | Sí | Sí 


| Edad y tamaño de los archivos | Sí | Sí 


| Capacidad para ejecutar unlink:task-controlling-governance-data.html["Informe de mapeo de datos"] | Sí | Sí 


| Página de investigación de datos para ver los detalles del archivo | Sí | No 


| Buscar nombres dentro de los archivos | Sí | No 


| Crearlink:task-using-policies.html["consultas guardadas"] que proporcionan resultados de búsqueda personalizados | Sí | No 


| Capacidad de ejecutar otros informes | Sí | No 


| Capacidad de ver metadatos de archivos** | No | Sí 
|===
{asterisk} La clasificación de datos no impone un límite en la cantidad de datos que puede escanear.  Cada agente de consola admite el escaneo y la visualización de 500 TiB de datos. Para escanear más de 500 TiB de datos,link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["instalar otro agente de consola"^] entonceslink:task-deploy-overview.html["Implementar otra instancia de clasificación de datos"] .  + La interfaz de usuario de la consola muestra datos de un solo conector.  Para obtener sugerencias sobre cómo ver datos de varios agentes de la consola, consultelink:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Trabajar con múltiples agentes de consola"^] .

{asterisk}{asterisk} Los siguientes metadatos se extraen de los archivos durante los escaneos de mapeo:

* Sistema
* Tipo de sistema
* Repositorio de almacenamiento
* Tipo de archivo
* Capacidad utilizada
* Número de archivos
* Tamaño del archivo
* Creación de archivos
* Último acceso al archivo
* Archivo modificado por última vez
* Hora de descubrimiento del archivo
* Extracción de permisos


.Diferencias en el panel de gobernanza:
[%collapsible]
====
[cols="40,25,25"]
|===
| Característica | Mapa y clasificación | Mapa 


| Datos obsoletos | Sí | Sí 


| Datos no comerciales | Sí | Sí 


| Archivos duplicados | Sí | Sí 


| Consultas guardadas predefinidas | Sí | No 


| Consultas guardadas predeterminadas | Sí | Sí 


| Informe de la DDA | Sí | Sí 


| Informe de mapeo | Sí | Sí 


| Detección del nivel de sensibilidad | Sí | No 


| Datos sensibles con amplios permisos | Sí | No 


| Permisos abiertos | Sí | Sí 


| La era de los datos | Sí | Sí 


| Tamaño de los datos | Sí | Sí 


| Categorías | Sí | No 


| Tipos de archivos | Sí | Sí 
|===
====
.Diferencias en el panel de cumplimiento:
[%collapsible]
====
[cols="40,25,25"]
|===
| Característica | Mapa y clasificación | Mapa 


| Información personal | Sí | No 


| Información personal sensible | Sí | No 


| Informe de evaluación de riesgos de privacidad | Sí | No 


| Informe HIPAA | Sí | No 


| Informe PCI DSS | Sí | No 
|===
====
.Diferencias en los filtros de investigación:
[%collapsible]
====
[cols="40,25,25"]
|===
| Característica | Mapa y clasificación | Mapa 


| Consultas guardadas | Sí | Sí 


| Tipo de sistema | Sí | Sí 


| Sistema | Sí | Sí 


| Repositorio de almacenamiento | Sí | Sí 


| Tipo de archivo | Sí | Sí 


| Tamaño del archivo | Sí | Sí 


| Hora de creación | Sí | Sí 


| Tiempo descubierto | Sí | Sí 


| Última modificación | Sí | Sí 


| Último acceso | Sí | Sí 


| Permisos abiertos | Sí | Sí 


| Ruta del directorio de archivos | Sí | Sí 


| Categoría | Sí | No 


| Nivel de sensibilidad | Sí | No 


| Número de identificadores | Sí | No 


| Datos personales | Sí | No 


| Datos personales sensibles | Sí | No 


| Titular de los datos | Sí | No 


| Duplicados | Sí | Sí 


| Estado de clasificación | Sí | El estado siempre es "Perspectivas limitadas" 


| Evento de análisis de escaneo | Sí | Sí 


| Hash de archivo | Sí | Sí 


| Número de usuarios con acceso | Sí | Sí 


| Permisos de usuario/grupo | Sí | Sí 


| Propietario del archivo | Sí | Sí 


| Tipo de directorio | Sí | Sí 
|===
====


== ¿Con qué rapidez escanea la clasificación de datos los datos?

La velocidad de escaneo se ve afectada por la latencia de la red, la latencia del disco, el ancho de banda de la red, el tamaño del entorno y los tamaños de distribución de archivos.

* Al realizar escaneos de solo mapeo, la clasificación de datos puede escanear entre 100 y 150 TiB de datos por día.
* Al realizar escaneos de mapas y clasificación, la clasificación de datos puede escanear entre 15 y 40 TiB de datos por día.

