---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: Planifique qué implementación de NetApp Data Classification se adapta a sus necesidades. 
---
= NetApp métodos de implementación de Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification admite varios métodos de implementación para diferentes requisitos de red y conectividad. Consulta los métodos disponibles para elegir la opción que mejor se adapte a tu entorno.

* link:task-deploy-cloud-compliance.html["Implementar en la nube usando la consola"] . La consola implementa la instancia de clasificación de datos en la misma red del proveedor de nube que el agente de la consola.
* link:task-deploy-compliance-onprem.html["Instalar en un host Linux con acceso a Internet"]. Instala Data Classification en un host Linux de tu red o en la nube. Esta opción puede ser útil si prefieres analizar sistemas ONTAP locales desde una instancia de Data Classification ubicada en tus instalaciones, pero no es obligatorio que la instancia esté en tus instalaciones.
* link:task-deploy-compliance-dark-site.html["Instalar en un host Linux en un sitio local sin acceso a Internet"], denominado _modo privado_. Este tipo de instalación, que utiliza un script de instalación, no tiene conectividad con la capa SaaS de Console.



TIP: Para las implementaciones locales de VMware vSphere, NetApp Data Classification admite una link:task-deploy-ova.html["despliegue con OVA"] simplificada.



[[on-premises-installation-script]]
== Script de instalación local

Ambos métodos de instalación utilizan un script de instalación. El script comprueba si el sistema y el entorno cumplen los requisitos previos. Si es así, se inicia la instalación.

Hay disponible un paquete de software independiente para comprobar si tu servidor Linux está preparado. Para ejecutar el paquete de verificación, consulta link:task-test-linux-system.html["verifica que tu host Linux está listo para instalar Data Classification"].
