---
sidebar: sidebar 
permalink: task-deploy-compliance-dark-site.html 
keywords: cloud compliance, bluexp, data sense, get started, web browser connectivity, cloud compliance access, privacy, linux, ubuntu, compliance, on-premises, dark site, upgrade, private mode, docker, podman, rhel, bluexp classification, classification, install, cloud data sense, linux host 
summary: 'Complete unos pocos pasos para instalar NetApp Data Classification en un host Linux en un sitio local que no tiene acceso a Internet, también conocido como "modo privado". Este tipo de instalación es perfecta para sus sitios seguros.' 
---
= Instalar NetApp Data Classification en un host Linux sin acceso a Internet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La instalación de NetApp Data Classification en un host Linux en un sitio local que no tiene acceso a Internet se conoce como _modo privado_.  Este tipo de instalación, que utiliza un script de instalación, no tiene conectividad con la capa SaaS de la consola de NetApp .


IMPORTANT: El modo privado de BlueXP (interfaz BlueXP heredada) generalmente se usa con entornos locales que no tienen conexión a Internet y con regiones de nube seguras, que incluyen AWS Secret Cloud, AWS Top Secret Cloud y Azure IL6. NetApp continúa brindando soporte a estos entornos con la interfaz BlueXP heredada. Para obtener documentación del modo privado en la interfaz heredada de BlueXP , consultelink:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["Documentación en PDF para el modo privado de BlueXP"^] .
