= Versión 1.42
:allow-uri-read: 




=== Versión 1.42

Esta versión de BlueXP classification incluye:

.Escaneo masivo para entornos de trabajo
La clasificación de BlueXP admite operaciones masivas para entornos de trabajo. Puedes elegir activar los análisis de Mapping, activar los análisis de Map & Classify, desactivar los análisis o crear una configuración personalizada en los volúmenes del entorno de trabajo. Si haces una selección para un volumen individual, esta anula la selección masiva. Para realizar una operación masiva, ve a la página de **Configuration** y haz tu selección.

.Descargar informe de investigación localmente
La BlueXP classification admite la posibilidad de descargar informes de investigación de datos localmente para verlos en el navegador. Si elige la opción local, la investigación de datos solo estará disponible en formato CSV y solo mostrará las primeras 10 000 filas de datos.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#create-the-data-investigation-report["Investigue los datos almacenados en su organización con la BlueXP classification"] .
