= Página de configuración mejorada
:allow-uri-read: 




=== Página de configuración mejorada

Data Classification ha actualizado y mejorado la página de Configuración, permitiendo una experiencia de uso mejorada para gestionar ajustes, sistemas, habilitar el escaneo y supervisar la salud del sistema. La nueva página de Configuración proporciona la funcionalidad existente en un formato más fácil de usar, además de la capacidad de filtrar sistemas por tipo, estado de error y estado de escaneo. La nueva página también proporciona un resumen de los sistemas conectados y vistas generales de los escaneos activos y configurados.

Revisa un link:https://youtu.be/_8YJ3KyZ7nI["video tutorial"^]. Para más información, consulta link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Escanea las fuentes de datos con Data Classification"^].



=== Función IAM de administrador de conformidad

Clasificación de datos ahora admite un rol de administrador de cumplimiento para gestionar los permisos en Clasificación de datos. El rol de administrador de cumplimiento no tiene acceso a recursos, incluidos los agentes de Console y los espacios de trabajo. Los usuarios con el rol de administrador de cumplimiento deben estar asociados con al menos otro rol.

Al instalar Data Classification, debes tener el rol de administrador de la plataforma de Console o el rol de administrador de Compliance.

Si eres un usuario existente, el acceso debería continuar normalmente. Por ejemplo, un rol de plataforma que tiene un rol de administrador de carpeta o proyecto tiene acceso existente.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Funciones de clasificación de datos"^].



=== Implementa Data Classification con OVA

NetApp Data Classification ahora admite la implementación con VMware Open Virtual Appliance (OVA), lo que ofrece una estrategia de implementación simplificada para entornos VMware vSphere locales.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Implementa Data Classification con OVA"^].
